services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyTunnels\:
        resource: '../../{Command,Repository,Service}'
        exclude: '../../Service/**/Abstract*.php'
        tags: ['controller.service_arguments']

    Wexample\SymfonyTunnels\Interface\TunnelSessionStorageInterface:
        alias: Wexample\SymfonyTunnels\Service\TunnelSessionService
