services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyTunnels\:
        resource: '../../{Service}'
        tags: ['controller.service_arguments']
